AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  AwsCfToken:
    Type: String
    NoEcho: true
    Description: Token for API auth (e.g. Cloudflare or custom); set via --parameter-overrides AwsCfToken=xxx when deploying
  AdminKey:
    Type: String
    NoEcho: true
    Description: Key for frontend admin access set via --parameter-overrides AdminKey=xxx when deploying

Resources:
  # S3 Bucket
  MyrestoSettingsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "myresto-settings-bucket-1f741eb9"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda Execution Role
  MyrestoSettingsLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3BucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub '${MyrestoSettingsBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt MyrestoSettingsBucket.Arn

  MyrestoSettingsService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for CRUD operations"
    Properties:
      Name: "myresto-settings-service"
      StageName: Prod
      Auth:
      Cors:
        AllowMethods: "'OPTIONS, POST, GET'"
        AllowHeaders: "'Content-Type, X-CF-Token, x-admin-key'"
        # AllowOrigin: "'http://localhost:5173'" 
        AllowOrigin: "'https://d3knrnqllqxltd.cloudfront.net'" 

      # Logging settings
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          DataTraceEnabled: true

  MyrestoSettingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 512
      Role: !GetAtt MyrestoSettingsLambdaExecutionRole.Arn
      Environment:
        Variables:
          # comes from --parameter-overrides
          AWS_CF_TOKEN: !Ref AwsCfToken  
          ADMIN_KEY: !Ref AdminKey
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref MyrestoSettingsTable
      Events:
        SettingsOptions:
          Type: Api
          Properties:
            Path: /settings
            Method: OPTIONS
            RestApiId: !Ref MyrestoSettingsService
        GetSettings:
          Type: Api
          Properties:
            Path: /settings
            Method: GET
            RestApiId: !Ref MyrestoSettingsService
        PostSetting:
          Type: Api
          Properties:
            Path: /settings
            Method: POST
            RestApiId: !Ref MyrestoSettingsService

        ValidateAdminKeyOptions:
          Type: Api
          Properties:
            Path: /settings/validateadminkey
            Method: OPTIONS
            RestApiId: !Ref MyrestoSettingsService
        ValidateAdminKey:
          Type: Api
          Properties:
            Path: /settings/validateadminkey
            Method: GET
            RestApiId: !Ref MyrestoSettingsService

        ThemesOptions:
          Type: Api
          Properties:
            Path: /settings/themes
            Method: OPTIONS
            RestApiId: !Ref MyrestoSettingsService
        GetThemes:
          Type: Api
          Properties:
            Path: /settings/themes
            Method: GET
            RestApiId: !Ref MyrestoSettingsService

        ThemeSettingsOptions:
          Type: Api
          Properties:
            Path: /settings/themesettings
            Method: OPTIONS
            RestApiId: !Ref MyrestoSettingsService
        GetThemeSettings:
          Type: Api
          Properties:
            Path: /settings/themesettings
            Method: GET
            RestApiId: !Ref MyrestoSettingsService
        PostThemeSettings:
          Type: Api
          Properties:
            Path: /settings/themesettings
            Method: POST
            RestApiId: !Ref MyrestoSettingsService                              

    Metadata:
      BuildMethod: makefile
